require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComentariosController do

  # This should return the minimal set of attributes required to create a valid
  # Comentario. As you add validations to Comentario, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all comentarios as @comentarios" do
      comentario = Comentario.create! valid_attributes
      get :index
      assigns(:comentarios).should eq([comentario])
    end
  end

  describe "GET show" do
    it "assigns the requested comentario as @comentario" do
      comentario = Comentario.create! valid_attributes
      get :show, :id => comentario.id.to_s
      assigns(:comentario).should eq(comentario)
    end
  end

  describe "GET new" do
    it "assigns a new comentario as @comentario" do
      get :new
      assigns(:comentario).should be_a_new(Comentario)
    end
  end

  describe "GET edit" do
    it "assigns the requested comentario as @comentario" do
      comentario = Comentario.create! valid_attributes
      get :edit, :id => comentario.id.to_s
      assigns(:comentario).should eq(comentario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comentario" do
        expect {
          post :create, :comentario => valid_attributes
        }.to change(Comentario, :count).by(1)
      end

      it "assigns a newly created comentario as @comentario" do
        post :create, :comentario => valid_attributes
        assigns(:comentario).should be_a(Comentario)
        assigns(:comentario).should be_persisted
      end

      it "redirects to the created comentario" do
        post :create, :comentario => valid_attributes
        response.should redirect_to(Comentario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comentario as @comentario" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comentario.any_instance.stub(:save).and_return(false)
        post :create, :comentario => {}
        assigns(:comentario).should be_a_new(Comentario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Comentario.any_instance.stub(:save).and_return(false)
        post :create, :comentario => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comentario" do
        comentario = Comentario.create! valid_attributes
        # Assuming there are no other comentarios in the database, this
        # specifies that the Comentario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Comentario.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => comentario.id, :comentario => {'these' => 'params'}
      end

      it "assigns the requested comentario as @comentario" do
        comentario = Comentario.create! valid_attributes
        put :update, :id => comentario.id, :comentario => valid_attributes
        assigns(:comentario).should eq(comentario)
      end

      it "redirects to the comentario" do
        comentario = Comentario.create! valid_attributes
        put :update, :id => comentario.id, :comentario => valid_attributes
        response.should redirect_to(comentario)
      end
    end

    describe "with invalid params" do
      it "assigns the comentario as @comentario" do
        comentario = Comentario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comentario.any_instance.stub(:save).and_return(false)
        put :update, :id => comentario.id.to_s, :comentario => {}
        assigns(:comentario).should eq(comentario)
      end

      it "re-renders the 'edit' template" do
        comentario = Comentario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Comentario.any_instance.stub(:save).and_return(false)
        put :update, :id => comentario.id.to_s, :comentario => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comentario" do
      comentario = Comentario.create! valid_attributes
      expect {
        delete :destroy, :id => comentario.id.to_s
      }.to change(Comentario, :count).by(-1)
    end

    it "redirects to the comentarios list" do
      comentario = Comentario.create! valid_attributes
      delete :destroy, :id => comentario.id.to_s
      response.should redirect_to(comentarios_url)
    end
  end

end
